version: '3.8'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: book_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "8080:3306"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://user:password@db/book_db

